import type { Service } from '@/types/content';

/**
 * The eight service lines.
 *
 * WRITING STYLE — plain English. Short sentences, everyday words, the benefit
 * stated before the method. Save deep technical detail for the body of the
 * service detail pages, where the reader has chosen to go.
 *
 * This array is the source of truth for the header dropdown, the footer
 * column, the Home services grid, and — from Phase 2 onward — the eight
 * `/services/[slug]` detail pages generated by `generateStaticParams`.
 * Adding a ninth service is an edit to this file and nothing else.
 */
export const services: Service[] = [
  {
    slug: 'web-development',
    name: 'Web Development',
    shortName: 'Web',
    tagline: 'Fast websites and web apps that handle real traffic',
    summary:
      'We build websites and web apps that load quickly and stay up when they get busy. Built to be easy to update later.',
    icon: 'web-development',
    accent: 'indigo',
    capabilities: [
      'Websites and web apps',
      'Online portals and dashboards',
      'Content management systems',
      'Speed and performance work',
      'Accessible to everyone',
    ],
    benefits: [
      {
        id: 'web-benefit-speed',
        title: 'Loads fast',
        description:
          'Slow pages lose customers. We set a speed target at the start and check every release against it.',
        icon: 'gauge',
      },
      {
        id: 'web-benefit-accessible',
        title: 'Works for everyone',
        description:
          'Your site works with a keyboard, a screen reader and a slow phone. We build it that way from day one.',
        icon: 'people',
      },
      {
        id: 'web-benefit-own',
        title: 'Yours to keep',
        description:
          'You get the code and full instructions. Nothing is locked to us, and there is no licence to keep paying.',
        icon: 'shield',
      },
    ],
    technologyIds: ['nextjs', 'react', 'typescript', 'node', 'postgres', 'vercel'],
    processStepIds: ['discover', 'define', 'design', 'build', 'launch', 'evolve'],
    caseStudySlugs: ['northwind-capital-platform', 'meridian-commerce-replatform'],
    faqIds: ['faq-timeline', 'faq-engagement', 'faq-handover'],
    order: 1,
    featured: true,
    seo: {
      title: 'Web Development Services',
      description:
        'Fast, reliable websites and web apps built to handle real traffic — and easy to update after launch.',
    },
  },
  {
    slug: 'mobile-app-development',
    name: 'Mobile App Development',
    shortName: 'Mobile',
    tagline: 'iPhone and Android apps your customers will keep',
    summary:
      'One app that works well on both iPhone and Android. We handle the app stores, the updates and the crash reports too.',
    icon: 'mobile-app',
    accent: 'cyan',
    capabilities: [
      'iPhone and Android apps',
      'Works without a signal',
      'Face ID and secure login',
      'App Store and Play Store setup',
      'Crash and speed monitoring',
    ],
    benefits: [
      {
        id: 'mobile-benefit-one-team',
        title: 'One app, both phones',
        description:
          'We share the code between iPhone and Android where it makes sense. You do not pay twice for the same feature.',
        icon: 'layers',
      },
      {
        id: 'mobile-benefit-release',
        title: 'Updates are easy',
        description:
          'Releases are automatic and tested. Pushing a new version stops being a stressful day.',
        icon: 'clock',
      },
      {
        id: 'mobile-benefit-stability',
        title: 'It does not crash',
        description:
          'We watch crash reports on every release and fix problems before your ratings drop.',
        icon: 'gauge',
      },
    ],
    technologyIds: ['react-native', 'swift', 'kotlin', 'typescript', 'firebase'],
    processStepIds: ['discover', 'define', 'design', 'build', 'launch', 'evolve'],
    caseStudySlugs: ['helix-health-cloud'],
    faqIds: ['faq-timeline', 'faq-team', 'faq-support'],
    order: 2,
    featured: true,
    seo: {
      title: 'Mobile App Development Services',
      description:
        'iPhone and Android apps built from one codebase, with app store setup and crash monitoring included.',
    },
  },
  {
    slug: 'ui-ux-design',
    name: 'UI/UX Design',
    shortName: 'Design',
    tagline: 'Designs that real people can actually use',
    summary:
      'We design your product, then test it with real users before anyone writes code. You get working parts, not just pictures.',
    icon: 'ui-ux-design',
    accent: 'violet',
    capabilities: [
      'User research and interviews',
      'Wireframes and prototypes',
      'Visual design',
      'Reusable component libraries',
      'Testing with real users',
    ],
    benefits: [
      {
        id: 'design-benefit-evidence',
        title: 'Tested before it is built',
        description:
          'We put early designs in front of real users. Fixing a problem now costs a lot less than fixing it later.',
        icon: 'target',
      },
      {
        id: 'design-benefit-system',
        title: 'Built to reuse',
        description:
          'You get a kit of buttons, forms and layouts. Your tenth screen looks as good as your first.',
        icon: 'layers',
      },
      {
        id: 'design-benefit-motion',
        title: 'Movement with a purpose',
        description:
          'Animation should show people what just happened. We never add it just to look busy.',
        icon: 'spark',
      },
    ],
    technologyIds: ['figma', 'storybook', 'react', 'typescript'],
    processStepIds: ['discover', 'define', 'design', 'build'],
    caseStudySlugs: ['meridian-commerce-replatform', 'northwind-capital-platform'],
    faqIds: ['faq-design-handover', 'faq-engagement'],
    order: 3,
    featured: true,
    seo: {
      title: 'UI/UX Design Services',
      description:
        'Product design tested with real users, handed over as working components your developers can use.',
    },
  },
  {
    slug: 'custom-software-development',
    name: 'Custom Software Development',
    shortName: 'Custom Software',
    tagline: 'Software built around how you already work',
    summary:
      'When off-the-shelf tools do not fit, we build one that does. It matches your process instead of forcing you to change it.',
    icon: 'custom-software',
    accent: 'teal',
    capabilities: [
      'Internal tools and dashboards',
      'Connecting systems together',
      'Replacing old software',
      'Moving your data across',
      'Automating manual work',
    ],
    benefits: [
      {
        id: 'custom-benefit-fit',
        title: 'Fits how you work',
        description:
          'Your team keeps its process. The software adapts to you, not the other way round.',
        icon: 'compass',
      },
      {
        id: 'custom-benefit-integrate',
        title: 'Talks to your other systems',
        description:
          'We connect it to the tools you already use, so nobody has to copy data by hand.',
        icon: 'layers',
      },
      {
        id: 'custom-benefit-maintain',
        title: 'Easy to change later',
        description:
          'We write it clearly and document it properly. In three years it will still be simple to update.',
        icon: 'shield',
      },
    ],
    technologyIds: ['typescript', 'node', 'python', 'postgres', 'graphql', 'aws'],
    processStepIds: ['discover', 'define', 'design', 'build', 'launch', 'evolve'],
    caseStudySlugs: ['atlas-logistics-control'],
    faqIds: ['faq-engagement', 'faq-ip', 'faq-handover'],
    order: 4,
    featured: true,
    seo: {
      title: 'Custom Software Development',
      description:
        'Bespoke software and internal tools built around your process, when off-the-shelf products do not fit.',
    },
  },
  {
    slug: 'cloud-and-devops',
    name: 'Cloud & DevOps',
    shortName: 'Cloud & DevOps',
    tagline: 'Servers that stay up and bills that make sense',
    summary:
      'We set up your cloud so releases are quick and safe, problems are easy to spot, and you know what you are paying for.',
    icon: 'cloud-devops',
    accent: 'indigo',
    capabilities: [
      'AWS, Azure and Google Cloud',
      'Automatic releases',
      'Backups and disaster recovery',
      'Alerts when something breaks',
      'Cutting cloud costs',
    ],
    benefits: [
      {
        id: 'cloud-benefit-deploy',
        title: 'Releases in minutes',
        description:
          'Shipping an update takes minutes and can be undone with one command if something looks wrong.',
        icon: 'clock',
      },
      {
        id: 'cloud-benefit-cost',
        title: 'A smaller bill',
        description:
          'Most reviews find a fifth to a third of cloud spend is wasted. We find it and turn it off.',
        icon: 'growth',
      },
      {
        id: 'cloud-benefit-see',
        title: 'You know when it breaks',
        description:
          'Alerts reach the right person straight away, so you hear it from us and not from a customer.',
        icon: 'gauge',
      },
    ],
    technologyIds: ['aws', 'terraform', 'kubernetes', 'docker', 'github-actions', 'grafana'],
    processStepIds: ['discover', 'define', 'build', 'launch', 'evolve'],
    caseStudySlugs: ['helix-health-cloud', 'atlas-logistics-control'],
    faqIds: ['faq-support', 'faq-security', 'faq-handover'],
    order: 5,
    featured: true,
    seo: {
      title: 'Cloud & DevOps Services',
      description:
        'Cloud setup, automatic releases and monitoring that keep your systems up and your bill predictable.',
    },
  },
  {
    slug: 'ai-and-automation',
    name: 'AI & Automation',
    shortName: 'AI & Automation',
    tagline: 'AI that saves real hours, not just headlines',
    summary:
      'We automate the jobs that eat your team’s day. We test the results properly, so you can trust what it produces.',
    icon: 'ai-automation',
    accent: 'violet',
    capabilities: [
      'Chatbots that use your own documents',
      'Reading and sorting paperwork',
      'Automating repetitive tasks',
      'Checking the results are correct',
      'Keeping a human in the loop',
    ],
    benefits: [
      {
        id: 'ai-benefit-eval',
        title: 'We check it works',
        description:
          'We build a test set first and score every answer against it. You see how accurate it is before it goes live.',
        icon: 'target',
      },
      {
        id: 'ai-benefit-scope',
        title: 'Starts with your problem',
        description:
          'We look at the job costing you hours, not at whatever was announced this week. Sometimes AI is not the answer.',
        icon: 'compass',
      },
      {
        id: 'ai-benefit-guardrails',
        title: 'A person stays in charge',
        description:
          'When the system is unsure, it asks a human. Every decision is recorded so you can check it later.',
        icon: 'shield',
      },
    ],
    technologyIds: ['python', 'typescript', 'postgres', 'aws', 'langchain'],
    processStepIds: ['discover', 'define', 'build', 'launch', 'evolve'],
    caseStudySlugs: ['atlas-logistics-control'],
    faqIds: ['faq-ai-scope', 'faq-security', 'faq-engagement'],
    order: 6,
    featured: true,
    seo: {
      title: 'AI & Automation Services',
      description:
        'Practical AI and automation that saves real hours, tested properly so you can trust the results.',
    },
  },
  {
    slug: 'it-consulting',
    name: 'IT Consulting',
    shortName: 'Consulting',
    tagline: 'A straight answer about what to do next',
    summary:
      'We review what you have and tell you what to fix first. You get a clear plan with costs, not a slide deck.',
    icon: 'it-consulting',
    accent: 'amber',
    capabilities: [
      'Reviewing your current setup',
      'Checking a company before you buy it',
      'Helping your team work faster',
      'Choosing the right technology',
      'Planning and budgeting',
    ],
    benefits: [
      {
        id: 'consult-benefit-plan',
        title: 'A plan with prices',
        description:
          'Every suggestion comes with a cost and an order to do it in. You can take it straight to your budget meeting.',
        icon: 'target',
      },
      {
        id: 'consult-benefit-fast',
        title: 'Weeks, not months',
        description:
          'A review takes two to four weeks. Long enough to be right, short enough to still matter.',
        icon: 'clock',
      },
      {
        id: 'consult-benefit-independent',
        title: 'No reason to oversell',
        description:
          'If what you have already works, we will say so. We have nothing to gain from telling you otherwise.',
        icon: 'handshake',
      },
    ],
    technologyIds: ['typescript', 'aws', 'postgres', 'kubernetes'],
    processStepIds: ['discover', 'define', 'evolve'],
    caseStudySlugs: ['meridian-commerce-replatform'],
    faqIds: ['faq-consulting-scope', 'faq-engagement', 'faq-pricing'],
    order: 7,
    featured: false,
    seo: {
      title: 'IT Consulting Services',
      description:
        'Independent reviews of your systems and team, ending in a clear plan with real costs attached.',
    },
  },
  {
    slug: 'maintenance-and-support',
    name: 'Maintenance & Support',
    shortName: 'Support',
    tagline: 'Someone to call when something breaks',
    summary:
      'We look after your software after launch. Agreed response times, security updates on schedule, and a monthly report you can read.',
    icon: 'maintenance-support',
    accent: 'rose',
    capabilities: [
      'Agreed response times',
      'Security and software updates',
      'Emergency fixes',
      'Speed and uptime monitoring',
      'Small improvements each month',
    ],
    benefits: [
      {
        id: 'support-benefit-sla',
        title: 'Response times in writing',
        description:
          'You know exactly how fast we answer, and who to escalate to. It is in the contract, not a promise.',
        icon: 'clock',
      },
      {
        id: 'support-benefit-proactive',
        title: 'Fixed before it breaks',
        description:
          'We update and patch on a schedule. Most problems never become problems.',
        icon: 'shield',
      },
      {
        id: 'support-benefit-continuity',
        title: 'People who know your system',
        description:
          'The same team that built it looks after it. Nobody has to learn it from scratch at 3am.',
        icon: 'people',
      },
    ],
    technologyIds: ['github-actions', 'grafana', 'aws', 'docker'],
    processStepIds: ['launch', 'evolve'],
    caseStudySlugs: ['helix-health-cloud'],
    faqIds: ['faq-support', 'faq-pricing', 'faq-handover'],
    order: 8,
    featured: false,
    seo: {
      title: 'Software Maintenance & Support',
      description:
        'Ongoing support with agreed response times, scheduled security updates and clear monthly reporting.',
    },
  },
];
