import type { Service } from '@/types/content';

/**
 * The eight service lines.
 *
 * WRITING STYLE — plain English. Short sentences, everyday words, the benefit
 * stated before the method. Save deep technical detail for the body of the
 * service detail pages, where the reader has chosen to go.
 *
 * This array is the source of truth for the header dropdown, the footer
 * column, the Home services grid, and — from Phase 2 onward — the eight
 * `/services/[slug]` detail pages generated by `generateStaticParams`.
 * Adding a ninth service is an edit to this file and nothing else.
 */
export const services: Service[] = [
  {
    slug: 'web-development',
    name: 'Web Development',
    shortName: 'Web',
    tagline: 'Fast websites and web apps that handle real traffic',
    summary:
      'We build websites and web apps that load quickly and stay up when they get busy. Built to be easy to update later.',
    icon: 'web-development',
    accent: 'indigo',
    capabilities: [
      'Websites and web apps',
      'Online portals and dashboards',
      'Content management systems',
      'Speed and performance work',
      'Accessible to everyone',
    ],
    benefits: [
      {
        id: 'web-benefit-speed',
        title: 'Loads fast',
        description:
          'Slow pages lose customers. We set a speed target at the start and check every release against it.',
        icon: 'gauge',
      },
      {
        id: 'web-benefit-accessible',
        title: 'Works for everyone',
        description:
          'Your site works with a keyboard, a screen reader and a slow phone. We build it that way from day one.',
        icon: 'people',
      },
      {
        id: 'web-benefit-own',
        title: 'Yours to keep',
        description:
          'You get the code and full instructions. Nothing is locked to us, and there is no licence to keep paying.',
        icon: 'shield',
      },
    ],
    technologyIds: ['nextjs', 'react', 'typescript', 'node', 'postgres', 'vercel'],
    processStepIds: ['discover', 'define', 'design', 'build', 'launch', 'evolve'],
    caseStudySlugs: ['vardhman-engineering-seo', 'shreeji-textiles-store'],
    faqIds: ['faq-timeline', 'faq-engagement', 'faq-handover'],
    order: 1,
    featured: true,
    seo: {
      title: 'Web Development Services',
      description:
        'Fast, reliable websites and web apps built to handle real traffic, and easy to update after launch.',
    },
  },
  {
    slug: 'mobile-app-development',
    name: 'Mobile App Development',
    shortName: 'Mobile',
    tagline: 'iPhone and Android apps your customers will keep',
    summary:
      'One app that works well on both iPhone and Android. We handle the app stores, the updates and the crash reports too.',
    icon: 'mobile-app',
    accent: 'cyan',
    capabilities: [
      'iPhone and Android apps',
      'Works without a signal',
      'Face ID and secure login',
      'App Store and Play Store setup',
      'Crash and speed monitoring',
    ],
    benefits: [
      {
        id: 'mobile-benefit-one-team',
        title: 'One app, both phones',
        description:
          'We share the code between iPhone and Android where it makes sense. You do not pay twice for the same feature.',
        icon: 'layers',
      },
      {
        id: 'mobile-benefit-release',
        title: 'Updates are easy',
        description:
          'Releases are automatic and tested. Pushing a new version stops being a stressful day.',
        icon: 'clock',
      },
      {
        id: 'mobile-benefit-stability',
        title: 'It does not crash',
        description:
          'We watch crash reports on every release and fix problems before your ratings drop.',
        icon: 'gauge',
      },
    ],
    technologyIds: ['react-native', 'swift', 'kotlin', 'typescript', 'firebase'],
    processStepIds: ['discover', 'define', 'design', 'build', 'launch', 'evolve'],
    caseStudySlugs: ['anand-diagnostics-booking'],
    faqIds: ['faq-timeline', 'faq-team', 'faq-support'],
    order: 2,
    featured: true,
    seo: {
      title: 'Mobile App Development Services',
      description:
        'iPhone and Android apps built from one codebase, with app store setup and crash monitoring included.',
    },
  },
  {
    slug: 'ui-ux-design',
    name: 'UI/UX Design',
    shortName: 'Design',
    tagline: 'Designs that real people can actually use',
    summary:
      'We design your product, then test it with real users before anyone writes code. You get working parts, not just pictures.',
    icon: 'ui-ux-design',
    accent: 'violet',
    capabilities: [
      'User research and interviews',
      'Wireframes and prototypes',
      'Visual design',
      'Reusable component libraries',
      'Testing with real users',
    ],
    benefits: [
      {
        id: 'design-benefit-evidence',
        title: 'Tested before it is built',
        description:
          'We put early designs in front of real users. Fixing a problem now costs a lot less than fixing it later.',
        icon: 'target',
      },
      {
        id: 'design-benefit-system',
        title: 'Built to reuse',
        description:
          'You get a kit of buttons, forms and layouts. Your tenth screen looks as good as your first.',
        icon: 'layers',
      },
      {
        id: 'design-benefit-motion',
        title: 'Movement with a purpose',
        description:
          'Animation should show people what just happened. We never add it just to look busy.',
        icon: 'spark',
      },
    ],
    technologyIds: ['figma', 'storybook', 'react', 'typescript'],
    processStepIds: ['discover', 'define', 'design', 'build'],
    caseStudySlugs: ['shreeji-textiles-store', 'vardhman-engineering-seo'],
    faqIds: ['faq-design-handover', 'faq-engagement'],
    order: 3,
    featured: true,
    seo: {
      title: 'UI/UX Design Services',
      description:
        'Product design tested with real users, handed over as working components your developers can use.',
    },
  },
  {
    slug: 'custom-software-development',
    name: 'Custom Software Development',
    shortName: 'Custom Software',
    tagline: 'Software built around how you already work',
    summary:
      'When off-the-shelf tools do not fit, we build one that does. It matches your process instead of forcing you to change it.',
    icon: 'custom-software',
    accent: 'teal',
    capabilities: [
      'Internal tools and dashboards',
      'Connecting systems together',
      'Replacing old software',
      'Moving your data across',
      'Automating manual work',
    ],
    benefits: [
      {
        id: 'custom-benefit-fit',
        title: 'Fits how you work',
        description:
          'Your team keeps its process. The software adapts to you, not the other way round.',
        icon: 'compass',
      },
      {
        id: 'custom-benefit-integrate',
        title: 'Talks to your other systems',
        description:
          'We connect it to the tools you already use, so nobody has to copy data by hand.',
        icon: 'layers',
      },
      {
        id: 'custom-benefit-maintain',
        title: 'Easy to change later',
        description:
          'We write it clearly and document it properly. In three years it will still be simple to update.',
        icon: 'shield',
      },
    ],
    technologyIds: ['typescript', 'node', 'python', 'postgres', 'graphql', 'aws'],
    processStepIds: ['discover', 'define', 'design', 'build', 'launch', 'evolve'],
    caseStudySlugs: ['rasoi-fresh-delivery'],
    faqIds: ['faq-engagement', 'faq-ip', 'faq-handover'],
    order: 4,
    featured: true,
    seo: {
      title: 'Custom Software Development',
      description:
        'Bespoke software and internal tools built around your process, when off-the-shelf products do not fit.',
    },
  },
  {
    slug: 'cloud-and-devops',
    name: 'Cloud & DevOps',
    shortName: 'Cloud & DevOps',
    tagline: 'Servers that stay up and bills that make sense',
    summary:
      'We set up your cloud so releases are quick and safe, problems are easy to spot, and you know what you are paying for.',
    icon: 'cloud-devops',
    accent: 'indigo',
    capabilities: [
      'AWS, Azure and Google Cloud',
      'Automatic releases',
      'Backups and disaster recovery',
      'Alerts when something breaks',
      'Cutting cloud costs',
    ],
    benefits: [
      {
        id: 'cloud-benefit-deploy',
        title: 'Releases in minutes',
        description:
          'Shipping an update takes minutes and can be undone with one command if something looks wrong.',
        icon: 'clock',
      },
      {
        id: 'cloud-benefit-cost',
        title: 'A smaller bill',
        description:
          'Most reviews find a fifth to a third of cloud spend is wasted. We find it and turn it off.',
        icon: 'growth',
      },
      {
        id: 'cloud-benefit-see',
        title: 'You know when it breaks',
        description:
          'Alerts reach the right person straight away, so you hear it from us and not from a customer.',
        icon: 'gauge',
      },
    ],
    technologyIds: ['aws', 'terraform', 'kubernetes', 'docker', 'github-actions', 'grafana'],
    processStepIds: ['discover', 'define', 'build', 'launch', 'evolve'],
    caseStudySlugs: ['anand-diagnostics-booking', 'rasoi-fresh-delivery'],
    faqIds: ['faq-support', 'faq-security', 'faq-handover'],
    order: 5,
    featured: true,
    seo: {
      title: 'Cloud & DevOps Services',
      description:
        'Cloud setup, automatic releases and monitoring that keep your systems up and your bill predictable.',
    },
  },
  {
    slug: 'ai-and-automation',
    name: 'AI & Automation',
    shortName: 'AI & Automation',
    tagline: 'AI that saves real hours, not just headlines',
    summary:
      'We automate the jobs that eat your team’s day. We test the results properly, so you can trust what it produces.',
    icon: 'ai-automation',
    accent: 'violet',
    capabilities: [
      'Chatbots that use your own documents',
      'Reading and sorting paperwork',
      'Automating repetitive tasks',
      'Checking the results are correct',
      'Keeping a human in the loop',
    ],
    benefits: [
      {
        id: 'ai-benefit-eval',
        title: 'We check it works',
        description:
          'We build a test set first and score every answer against it. You see how accurate it is before it goes live.',
        icon: 'target',
      },
      {
        id: 'ai-benefit-scope',
        title: 'Starts with your problem',
        description:
          'We look at the job costing you hours, not at whatever was announced this week. Sometimes AI is not the answer.',
        icon: 'compass',
      },
      {
        id: 'ai-benefit-guardrails',
        title: 'A person stays in charge',
        description:
          'When the system is unsure, it asks a human. Every decision is recorded so you can check it later.',
        icon: 'shield',
      },
    ],
    technologyIds: ['python', 'typescript', 'postgres', 'aws', 'langchain'],
    processStepIds: ['discover', 'define', 'build', 'launch', 'evolve'],
    caseStudySlugs: ['rasoi-fresh-delivery'],
    faqIds: ['faq-ai-scope', 'faq-security', 'faq-engagement'],
    order: 6,
    featured: true,
    seo: {
      title: 'AI & Automation Services',
      description:
        'Practical AI and automation that saves real hours, tested properly so you can trust the results.',
    },
  },
  {
    slug: 'it-consulting',
    name: 'IT Consulting',
    shortName: 'Consulting',
    tagline: 'A straight answer about what to do next',
    summary:
      'We review what you have and tell you what to fix first. You get a clear plan with costs, not a slide deck.',
    icon: 'it-consulting',
    accent: 'amber',
    capabilities: [
      'Reviewing your current setup',
      'Checking a company before you buy it',
      'Helping your team work faster',
      'Choosing the right technology',
      'Planning and budgeting',
    ],
    benefits: [
      {
        id: 'consult-benefit-plan',
        title: 'A plan with prices',
        description:
          'Every suggestion comes with a cost and an order to do it in. You can take it straight to your budget meeting.',
        icon: 'target',
      },
      {
        id: 'consult-benefit-fast',
        title: 'Weeks, not months',
        description:
          'A review takes two to four weeks. Long enough to be right, short enough to still matter.',
        icon: 'clock',
      },
      {
        id: 'consult-benefit-independent',
        title: 'No reason to oversell',
        description:
          'If what you have already works, we will say so. We have nothing to gain from telling you otherwise.',
        icon: 'handshake',
      },
    ],
    technologyIds: ['typescript', 'aws', 'postgres', 'kubernetes'],
    processStepIds: ['discover', 'define', 'evolve'],
    caseStudySlugs: ['shreeji-textiles-store'],
    faqIds: ['faq-consulting-scope', 'faq-engagement', 'faq-pricing'],
    order: 7,
    featured: false,
    seo: {
      title: 'IT Consulting Services',
      description:
        'Independent reviews of your systems and team, ending in a clear plan with real costs attached.',
    },
  },
  {
    slug: 'maintenance-and-support',
    name: 'Maintenance & Support',
    shortName: 'Support',
    tagline: 'Someone to call when something breaks',
    summary:
      'We look after your software after launch. Agreed response times, security updates on schedule, and a monthly report you can read.',
    icon: 'maintenance-support',
    accent: 'rose',
    capabilities: [
      'Agreed response times',
      'Security and software updates',
      'Emergency fixes',
      'Speed and uptime monitoring',
      'Small improvements each month',
    ],
    benefits: [
      {
        id: 'support-benefit-sla',
        title: 'Response times in writing',
        description:
          'You know exactly how fast we answer, and who to escalate to. It is in the contract, not a promise.',
        icon: 'clock',
      },
      {
        id: 'support-benefit-proactive',
        title: 'Fixed before it breaks',
        description:
          'We update and patch on a schedule. Most problems never become problems.',
        icon: 'shield',
      },
      {
        id: 'support-benefit-continuity',
        title: 'People who know your system',
        description:
          'The same team that built it looks after it. Nobody has to learn it from scratch at 3am.',
        icon: 'people',
      },
    ],
    technologyIds: ['github-actions', 'grafana', 'aws', 'docker'],
    processStepIds: ['launch', 'evolve'],
    caseStudySlugs: ['anand-diagnostics-booking'],
    faqIds: ['faq-support', 'faq-pricing', 'faq-handover'],
    order: 8,
    featured: false,
    seo: {
      title: 'Software Maintenance & Support',
      description:
        'Ongoing support with agreed response times, scheduled security updates and clear monthly reporting.',
    },
  },

  /* -----------------------------------------------------------------------
     The marketing and infrastructure side of the agency.

     These six are the services the original mediaradical.in leads with. The
     source describes each in a single sentence; the copy here is rewritten
     and expanded to the depth the rest of the site carries, in the same plain
     English. Nothing is lifted verbatim.
     ----------------------------------------------------------------------- */
  {
    slug: 'seo',
    name: 'SEO',
    shortName: 'SEO',
    tagline: 'Get found by people already looking for you',
    summary:
      'We improve where your site appears in Google for the searches that actually bring customers. No tricks, just the work that moves rankings.',
    icon: 'seo',
    accent: 'indigo',
    capabilities: [
      'Keyword and competitor research',
      'On-page and technical SEO',
      'Local and Google Business Profile',
      'Content planning',
      'Monthly ranking reports',
    ],
    benefits: [
      {
        id: 'seo-benefit-intent',
        title: 'Traffic that converts',
        description:
          'We target searches with buying intent, not the ones with the biggest numbers. Fewer visitors, more enquiries.',
        icon: 'target',
      },
      {
        id: 'seo-benefit-technical',
        title: 'The technical work too',
        description:
          'Speed, mobile, crawlability and structured data. Most agencies stop at keywords, and that is where rankings are usually lost.',
        icon: 'gauge',
      },
      {
        id: 'seo-benefit-report',
        title: 'Reports you can read',
        description:
          'Every month: what moved, what we did, what is next. Plain English, with the numbers attached.',
        icon: 'growth',
      },
    ],
    technologyIds: ['nextjs', 'wordpress', 'gcp'],
    processStepIds: ['discover', 'define', 'build', 'evolve'],
    caseStudySlugs: ['shreeji-textiles-store'],
    faqIds: ['faq-engagement', 'faq-pricing', 'faq-timeline'],
    order: 9,
    featured: true,
    seo: {
      title: 'SEO Services',
      description:
        'Search engine optimisation aimed at searches with buying intent: technical, on-page and local, reported every month.',
    },
  },
  {
    slug: 'ppc-and-google-ads',
    name: 'PPC & Google Ads',
    shortName: 'Paid Ads',
    tagline: 'Ads that pay for themselves',
    summary:
      'Search, shopping and social campaigns built around what a customer is actually worth to you, so you can tell whether the spend is working.',
    icon: 'ads',
    accent: 'rose',
    capabilities: [
      'Google Search and Shopping',
      'Meta and LinkedIn ads',
      'Landing pages built to convert',
      'Conversion tracking setup',
      'Budget and bid management',
    ],
    benefits: [
      {
        id: 'ppc-benefit-tracking',
        title: 'Tracking set up first',
        description:
          'We do not spend a rupee until conversions are tracked correctly. Without that you are optimising blind.',
        icon: 'target',
      },
      {
        id: 'ppc-benefit-landing',
        title: 'The landing page matters more',
        description:
          'Good ads pointed at a slow page waste money. We build the page as part of the campaign, not after it.',
        icon: 'gauge',
      },
      {
        id: 'ppc-benefit-honest',
        title: 'We will tell you to stop',
        description:
          'If the numbers do not work for your margins, we say so rather than keep charging a management fee.',
        icon: 'handshake',
      },
    ],
    technologyIds: ['nextjs', 'gcp'],
    processStepIds: ['discover', 'define', 'launch', 'evolve'],
    caseStudySlugs: ['shreeji-textiles-store'],
    faqIds: ['faq-pricing', 'faq-engagement'],
    order: 10,
    featured: true,
    seo: {
      title: 'PPC & Google Ads Management',
      description:
        'Paid search and social campaigns with conversion tracking set up first and landing pages built as part of the work.',
    },
  },
  {
    slug: 'social-media-marketing',
    name: 'Social Media Marketing',
    shortName: 'Social',
    tagline: 'A feed worth following',
    summary:
      'Planning, content and community management on the platforms your customers actually use, with a calendar you can see weeks ahead.',
    icon: 'social-media',
    accent: 'violet',
    capabilities: [
      'Content strategy and calendar',
      'Post design and copywriting',
      'Reels and short video',
      'Community management',
      'Performance reporting',
    ],
    benefits: [
      {
        id: 'social-benefit-plan',
        title: 'Planned, not panicked',
        description:
          'You approve a month at a time. Nobody is writing a caption at 9pm because something has to go out.',
        icon: 'clock',
      },
      {
        id: 'social-benefit-brand',
        title: 'Consistent to your brand',
        description:
          'One set of templates, one tone of voice. Your tenth post looks like it came from the same company as your first.',
        icon: 'layers',
      },
      {
        id: 'social-benefit-measure',
        title: 'Measured against something',
        description:
          'Reach and likes are the easy numbers. We report the ones tied to enquiries and sales.',
        icon: 'growth',
      },
    ],
    technologyIds: ['figma'],
    processStepIds: ['discover', 'define', 'design', 'evolve'],
    caseStudySlugs: [],
    faqIds: ['faq-engagement', 'faq-pricing'],
    order: 11,
    featured: true,
    seo: {
      title: 'Social Media Marketing',
      description:
        'Strategy, content and community management with an approved calendar and reporting tied to enquiries.',
    },
  },
  {
    slug: 'domain-and-hosting',
    name: 'Domain & Hosting',
    shortName: 'Hosting',
    tagline: 'Your address online, and somewhere reliable to keep it',
    summary:
      'Domain registration, managed hosting, SSL and backups. Set up properly once, then looked after so you never think about it.',
    icon: 'domain-hosting',
    accent: 'teal',
    capabilities: [
      'Domain registration and transfer',
      'Managed hosting',
      'SSL certificates',
      'Daily backups',
      'Uptime monitoring',
    ],
    benefits: [
      {
        id: 'hosting-benefit-uptime',
        title: 'It stays up',
        description:
          'Monitored around the clock. If something goes down, we usually know before you do.',
        icon: 'shield',
      },
      {
        id: 'hosting-benefit-backup',
        title: 'Backups you can restore',
        description:
          'Taken daily and tested. A backup nobody has ever restored from is not a backup.',
        icon: 'clock',
      },
      {
        id: 'hosting-benefit-own',
        title: 'Registered in your name',
        description:
          'Your domain and accounts belong to you. Some agencies hold the logins; we hand them over.',
        icon: 'handshake',
      },
    ],
    technologyIds: ['cloudflare', 'nginx', 'gcp', 'vercel'],
    processStepIds: ['define', 'launch', 'evolve'],
    caseStudySlugs: [],
    faqIds: ['faq-support', 'faq-ip'],
    order: 12,
    featured: false,
    seo: {
      title: 'Domain & Hosting Services',
      description:
        'Domain registration and managed hosting with SSL, daily tested backups and uptime monitoring.',
    },
  },
  {
    slug: 'email-solutions',
    name: 'Email Solutions',
    shortName: 'Email',
    tagline: 'Email at your own domain, set up right',
    summary:
      'Google Workspace, Microsoft 365 or standard business email, migrated, configured and protected so your messages reach the inbox.',
    icon: 'email',
    accent: 'cyan',
    capabilities: [
      'Google Workspace setup',
      'Microsoft 365 setup',
      'Migration from an old provider',
      'SPF, DKIM and DMARC',
      'Shared mailboxes and groups',
    ],
    benefits: [
      {
        id: 'email-benefit-deliver',
        title: 'Lands in the inbox',
        description:
          'SPF, DKIM and DMARC configured properly. Without them your mail quietly goes to spam.',
        icon: 'target',
      },
      {
        id: 'email-benefit-migrate',
        title: 'Nothing lost in the move',
        description:
          'Existing mail, contacts and calendars come across, and migrations run outside working hours.',
        icon: 'layers',
      },
      {
        id: 'email-benefit-trust',
        title: 'Looks professional',
        description:
          'An address at your own domain instead of a free one. A small thing customers notice.',
        icon: 'shield',
      },
    ],
    technologyIds: ['gcp'],
    processStepIds: ['define', 'launch'],
    caseStudySlugs: [],
    faqIds: ['faq-support'],
    order: 13,
    featured: false,
    seo: {
      title: 'Business Email Solutions',
      description:
        'Google Workspace and Microsoft 365 setup and migration, with SPF, DKIM and DMARC configured for deliverability.',
    },
  },
  {
    slug: 'ecommerce-and-crm',
    name: 'Ecommerce & CRM',
    shortName: 'Ecommerce',
    tagline: 'Sell online and keep track of who bought',
    summary:
      'Online stores with payments, stock and shipping wired up, connected to a CRM so every enquiry and order sits in one place.',
    icon: 'ecommerce',
    accent: 'amber',
    capabilities: [
      'Shopify and WooCommerce stores',
      'Payment gateway integration',
      'Stock and order management',
      'CRM setup and integration',
      'Abandoned cart recovery',
    ],
    benefits: [
      {
        id: 'ecom-benefit-checkout',
        title: 'A checkout that finishes',
        description:
          'Most carts are lost at payment. We keep the steps short and the page fast, then measure where people drop out.',
        icon: 'gauge',
      },
      {
        id: 'ecom-benefit-stock',
        title: 'Stock that matches reality',
        description:
          'Your store, your warehouse and your accounts show the same numbers, because they update from one source.',
        icon: 'layers',
      },
      {
        id: 'ecom-benefit-crm',
        title: 'Every customer in one place',
        description:
          'Orders, enquiries and conversations together, so your team can answer without asking three people first.',
        icon: 'people',
      },
    ],
    technologyIds: ['shopify', 'wordpress', 'nextjs', 'postgres'],
    processStepIds: ['discover', 'define', 'design', 'build', 'launch', 'evolve'],
    caseStudySlugs: ['shreeji-textiles-store'],
    faqIds: ['faq-timeline', 'faq-pricing', 'faq-support'],
    order: 14,
    featured: true,
    seo: {
      title: 'Ecommerce & CRM Development',
      description:
        'Online stores with payments, stock and shipping connected to a CRM, so orders and enquiries live in one place.',
    },
  },
];
